-- 코드를 입력하세요
-- 도서 판매 데이터 기준
-- 저자별 카테고리별 -> 매출액 (TOTAL_SALES = 판매량 * 판매가)
-- AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES 조회
-- AUTHOR_ID ASC, CATEGORY DESC
SELECT  A.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(S.SALES * B.PRICE) AS TOTAL_SALES
  FROM  BOOK AS B
  JOIN  AUTHOR AS A
    ON  B.AUTHOR_ID = A.AUTHOR_ID
  JOIN  BOOK_SALES AS S
    ON  S.BOOK_ID = B.BOOK_ID
 WHERE  S.SALES_DATE LIKE '2022-01%'
 GROUP
    BY  A.AUTHOR_ID, B.CATEGORY
 ORDER
    BY  A.AUTHOR_ID ASC, B.CATEGORY DESC;