-- 코드를 작성해주세요
SELECT  T.ID
  FROM  ECOLI_DATA AS F
  LEFT
  JOIN  ECOLI_DATA AS S
    ON  F.ID = S.PARENT_ID
  LEFT
  JOIN  ECOLI_DATA AS T
    ON  S.ID = T.PARENT_ID
 WHERE  F.PARENT_ID IS NULL
   AND  T.ID IS NOT NULL
 ORDER
    BY  T.ID;