SELECT  NAME
  FROM  STUDENTS AS S
  JOIN  FRIENDS AS F
    ON  S.ID = F.ID
  JOIN  PACKAGES AS P
    ON  F.ID = P.ID
  JOIN  PACKAGES AS P1
    ON  F.FRIEND_ID = P1.ID
 WHERE  P1.SALARY > P.SALARY
 ORDER
    BY  P1.SALARY;