-- 코드를 입력하세요
WITH MaxFavorites AS (
    SELECT 
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAV
    FROM 
        REST_INFO
    GROUP BY 
        FOOD_TYPE
)
SELECT 
    R.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    R.FAVORITES
FROM 
    REST_INFO AS R
JOIN 
    MaxFavorites AS M
ON 
    R.FOOD_TYPE = M.FOOD_TYPE AND R.FAVORITES = M.MAX_FAV
ORDER BY 
    R.FOOD_TYPE DESC;