-- 코드를 입력하세요
-- 2022-04-13 취소되지 않은 CS 진료 예약 내역
SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a 
    JOIN PATIENT p ON a.PT_NO = p.PT_NO
    JOIN DOCTOR d ON MDDR_ID = DR_ID
WHERE APNT_CNCL_YN = 'N'
    AND a.MCDP_CD = 'CS'
    AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD