-- 코드를 입력하세요
/*
1. HOUR(DATETIME)
2. GROUP BY HOUR
3. COUNT(ANIMAL_ID)
*/
WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
        FROM TIME
        WHERE HOUR < 23
)
SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM TIME T
    LEFT JOIN (SELECT *, HOUR(DATETIME) AS HOUR
            FROM ANIMAL_OUTS) O
      ON T.HOUR = O.HOUR
    GROUP BY 1
    ORDER BY 1