-- 코드를 입력하세요
/*
1. HOUR(DATETIME)
2. GROUP BY HOUR
3. COUNT(ANIMAL_ID)
*/
SELECT  HOUR(DATETIME) AS HOUR,
        COUNT(ANIMAL_ID) AS COUNT
  FROM  ANIMAL_OUTS
 GROUP
    BY  HOUR(DATETIME)
 ORDER
    BY  HOUR ASC;