-- CODE, SKILL_CODE
-- CATEGORY = 'Front End'
-- ID, EMAIL, FIRST_NAME, LAST_NAME
-- ID ASC

SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS AS D
JOIN
    SKILLCODES AS S
    ON (S.CODE & D.SKILL_CODE) = S.CODE
WHERE
    CATEGORY = 'Front End'
GROUP BY
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY
    D.ID ASC;