-- 코드를 작성해주세요
-- 자식이 부모의 형질을 모두 보유한 대장균의 ID
SELECT  C.ID
        ,C.GENOTYPE
        ,P.GENOTYPE AS PARENT_GENOTYPE
  FROM  ECOLI_DATA AS C
  JOIN  ECOLI_DATA AS P
    ON  C.PARENT_ID = P.ID
 WHERE  (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
 ORDER
    BY  C.ID ASC;

# SELECT *
#   FROM ECOLI_DATA E1
#   JOIN ECOLI_DATA E2
#     ON E1.ID = E2.PARENT_ID