SELECT  C.COMPANY_CODE,
        C.FOUNDER,
        COALESCE(LM.LEAD_MANAGER_COUNT, 0) AS LEAD_MANAGER_COUNT,
        COALESCE(SM.SENIOR_MANAGER_COUNT, 0) AS SENIOR_MANAGER_COUNT,
        COALESCE(M.MANAGER_COUNT, 0) AS MANAGER_COUNT,
        COALESCE(E.EMPLOYEE_COUNT, 0) AS EMPLOYEE_COUNT
  FROM  COMPANY AS C
  LEFT
  JOIN  (
          SELECT  COMPANY_CODE,
                  COUNT(DISTINCT LEAD_MANAGER_CODE) AS LEAD_MANAGER_COUNT
            FROM  LEAD_MANAGER
           GROUP
              BY  COMPANY_CODE
            ) AS  LM
    ON  C.COMPANY_CODE = LM.COMPANY_CODE
  LEFT
  JOIN (
          SELECT  COMPANY_CODE,
                  COUNT(DISTINCT SENIOR_MANAGER_CODE) AS SENIOR_MANAGER_COUNT
            FROM  SENIOR_MANAGER
           GROUP
              BY  COMPANY_CODE
            ) AS  SM   
    ON  C.COMPANY_CODE = SM.COMPANY_CODE
  LEFT
  JOIN (
          SELECT  COMPANY_CODE,
                  COUNT(DISTINCT MANAGER_CODE) AS MANAGER_COUNT
            FROM  MANAGER
           GROUP
              BY  COMPANY_CODE
            ) AS  M
    ON  C.COMPANY_CODE = M.COMPANY_CODE
  LEFT
  JOIN (
          SELECT  COMPANY_CODE,
                  COUNT(DISTINCT EMPLOYEE_CODE) AS EMPLOYEE_COUNT
            FROM  EMPLOYEE
           GROUP
              BY  COMPANY_CODE
            ) AS  E
    ON  C.COMPANY_CODE = E.COMPANY_CODE
 ORDER
    BY  C.COMPANY_CODE ASC;